export type ProjectData = {
  id: number;
  name: string;
  slug: string;
  category: string;
  imagePath: string;
  imagesPath?: string[];
  videoPath?: string;
  isWide: boolean;
  isVideo?: boolean;
}

export const projectsData: ProjectData[] = [
  {
    id: 1, // Nuovo progetto
    name: 'MONTBLANC',
    slug: 'montblanc',
    category: 'CREATIVE DIRECTOR: MARCO TOMMASETTA, PH: MARIANO VIVANCO, STYLIST: PAOLO TURINA, MAIN PRODUCTION: JN PRODUCTION',
    imagePath: '/assets/projects-thumbnail/montblanc-cover.jpg',
    isWide: true,
    imagesPath: [
      '/assets/48/1.jpg',
      '/assets/48/2.jpg',
      '/assets/48/3.jpg',
      '/assets/48/4.jpg',
      '/assets/48/5.jpg',
      '/assets/48/6.jpg',
    ],
  },
  {
    id: 3,
    name: 'ARMANI JUNIOR CAMPING SS2024',
    slug: 'armani-junior-camping-ss2024',
    category: 'CREATIVE DIRECTION: ALAN PRADA, PH: GIOVANNI CORABI, STYLIST: GIUSEPPE SILEO',
    imagePath: '/assets/projects-thumbnail/GA-copertina.jpg',
    isWide: false,
    imagesPath: [
      '/assets/47/1.jpg',
      '/assets/47/2.jpg',
      '/assets/47/3.jpg',
      '/assets/47/4.jpg',
      '/assets/47/5.jpg',
      '/assets/47/6.jpg',
      '/assets/47/7.jpg',
    ],
  },
  {
    id: 2,
    name: 'PINKO FW2024',
    slug: 'pinko-fw2024',
    category: 'TESTIMONIAL: MARIACARLA BOSCONO, ART DIRECTOR & STYLIST: LORENZO POSOCCO, PH: PABLO DI PRIMA',
    imagePath: '/assets/projects-thumbnail/pinkocover.jpg',
    isWide: false,
    imagesPath: [
      '/assets/45/1.jpg',
      '/assets/45/2.jpg',
      '/assets/45/3.jpg',
      '/assets/45/4.jpg',
      '/assets/45/5.jpg',
      '/assets/45/6.jpg',
      '/assets/45/7.jpg',
      '/assets/45/8.jpg',
      '/assets/45/9.jpg',
      '/assets/45/10.jpg',
    ],
  },
  {
    id: 4,
    name: 'EA BEACHWEAR SS2024',
    slug: 'ea-beachwear-ss2024',
    category: 'CREATIVE DIRECTION: ALAN PRADA, PH: ILYRA LIPKIN, STYLIST: GIUSEPPE SILEO',
    imagePath: '/assets/projects-thumbnail/Ea-cover.jpg',
    isWide: false,
    imagesPath: [
      '/assets/46/1.jpg',
      '/assets/46/2.jpg',
      '/assets/46/3.jpg',
      '/assets/46/4.jpg',
      '/assets/46/5.jpg',
      '/assets/46/6.jpg',
    ],
  },
  {
    id: 5,
    name: 'FAY SS24',
    slug: 'fay-ss24',
    category:
      'PH: FEDERICO SORRENTINO,\nSTYLIST: ALESSIA GIACOBINO\nLOCATION GARDA LAKE (IT)',
    imagePath: '/assets/projects-thumbnail/fay-ss24.jpg',
    isWide: false,
    imagesPath: [
      '/assets/41/1.jpg',
      '/assets/41/2.jpg',
      '/assets/41/3.jpg',
      '/assets/41/4.jpg',
      '/assets/41/5.jpg',
      '/assets/41/6.jpg',
      '/assets/41/7.jpg',
      '/assets/41/8.jpg',
      '/assets/41/9.jpg',
      '/assets/41/10.jpg',
      '/assets/41/11.jpg',
    ],
  },
  {
    id: 9,
    name: 'ELLE US – ISLAND FANTASY',
    slug: 'elle-us-island-fantasy',
    category:
      'PH: CÉSAR SEGARRA, \nSTYLIST: ANASTASIA BARBIERI, \nMAIN PRODUCTION: LOUIS2 \nLOCATION: ISOLA BELLA \n(MAGGIORE LAKE)',
    imagePath: '/assets/projects-thumbnail/elleus-island-fantasy-01.jpg',
    isWide: true,
    imagesPath: [
      '/assets/6/1.jpg',
      '/assets/6/2.jpg',
      '/assets/6/3.jpg',
      '/assets/6/4.jpg',
      '/assets/6/5.jpg',
      '/assets/6/6.jpg',
      '/assets/6/7.jpg',
    ],
  },
  {
    id: 10,
    name: 'MADAME – CHE BELLA!',
    slug: 'madame-che-bella!',
    category:
      'PH: ADRIANO RUSSO, \nSTYLIST: KONSTANTIN SPACHIS, \n LOCATION: PANTELLERIA (IT)',
    imagePath: '/assets/projects-thumbnail/madame-chebella-01.jpg',
    isWide: false,
    imagesPath: [
      `/assets/7/1.jpg`,
      `/assets/7/2.jpg`,
      `/assets/7/3.jpg`,
      `/assets/7/4.jpg`,
      `/assets/7/5.jpg`,
      `/assets/7/6.jpg`,
    ],
  },
  {
    id: 11,
    name: 'FAY FW2023',
    slug: 'fay-fw23',
    category:
      'PH: NICOLO PARSENZIANI, \nSTYLIST: ALESSIA GIACOBINO \nE MIGUEL ARNAU',
    imagePath: '/assets/projects-thumbnail/fay.jpg',
    isWide: false,
    imagesPath: [
      `/assets/8/1.jpg`,
      `/assets/8/2.jpg`,
      `/assets/8/3.jpg`,
      `/assets/8/4.jpg`,
      `/assets/8/5.jpg`,
    ],
  },
  {
    id: 12,
    name: 'LUISAVIAROMA',
    slug: 'luisaviaroma',
    category:
      'PH: ADRIANO RUSSO, \nSTYLIST: FLAMINIA MINNEO \nE ANDREA SANGIORGI, \nLOCATION: PANTELLERIA (IT)',
    imagePath: '/assets/projects-thumbnail/luisaviaroma-01.jpg',
    isWide: false,
    imagesPath: [
      `/assets/9/1.jpg`,
      `/assets/9/2.jpg`,
      `/assets/9/3.jpg`,
      `/assets/9/4.jpg`,
      `/assets/9/5.jpg`,
      `/assets/9/6.jpg`,
      `/assets/9/7.jpg`,
    ],
  },
  {
    id: 13,
    name: 'CORNELIANI SS2023',
    slug: 'corneliani-ss23',
    category:
      'PH: MARCO IMPERATORE, \nSTYLIST: EMIL REBEK, \nART DIRECTOR: ILLUMINAM AGENCY',
    imagePath: '/assets/projects-thumbnail/corneliani-05-01.jpg',
    isWide: true,
    imagesPath: [
      `/assets/10/1.jpg`,
      `/assets/10/2.jpg`,
      `/assets/10/3.jpg`,
      `/assets/10/4.jpg`,
      `/assets/10/5.jpg`,
    ],
  },
  {
    id: 14,
    name: 'LOUIS VUITTON THE BOOK',
    slug: 'louis-vuitton-the-book',
    category:
      'PH: ANGELO PENNETTA, \nSTYLIST: EMILIE KAREH, \nMAIN PRODUCTION: LOUIS2\nLOCATION: VENICE (IT)',
    imagePath: '/assets/projects-thumbnail/louis-vuitton-01.jpg',
    isWide: false,
    imagesPath: [
      `/assets/11/1.jpg`,
      `/assets/11/2.jpg`,
    ],
  },
  {
    id: 15,
    name: 'MADAME – VIVA PALOMA',
    slug: 'madame-viva-paloma',
    category: 'PH: ADRIANO RUSSO, \nSTYLIST: KONSTANTIN SPACHIS',
    imagePath: '/assets/projects-thumbnail/madame-vivapaloma-01.jpg',
    isWide: false,
    imagesPath: [
      `/assets/12/7.jpg`,
      `/assets/12/1.jpg`,
      `/assets/12/2.jpg`,
      `/assets/12/3.jpg`,
      `/assets/12/4.jpg`,
      `/assets/12/5.jpg`,
      `/assets/12/6.jpg`,
    ],
  },
  {
    id: 16,
    name: 'TISSOT SEASTAR 2021',
    slug: 'tissot-seastar-2021',
    category:
      'PH: ADRIANO RUSSO, \nSTYLIST: GIULIO CASAGRANDE\n LOCATION:IBIZA (ES)',
    imagePath: '/assets/projects-thumbnail/Tissot-02.jpg',
    isWide: false,
    imagesPath: [
      `/assets/13/1.jpg`,
      `/assets/13/2.jpg`,
    ],
  },
  {
    id: 17,
    name: 'TISSOT SEASTAR 2021 Video Campaign',
    slug: 'tissot-video',
    category: 'PH: ADRIANO RUSSO \nSTYLIST: GIULIO CASAGRANDE \n LOCATION: IBIZA (ES)',
    imagePath: '/assets/projects-thumbnail/Tissot-01.jpg',
    videoPath: '/assets/4/tissot.mp4',
    isWide: false,
    isVideo: true,
  },
  {
    id: 18,
    name: 'THE SUNDAY TIMES STYLE',
    slug: 'the-sunday-times-style',
    category: 'PH: ADRIANO RUSSO, \nTALENT: JORDAN ALEXANDER',
    imagePath: '/assets/projects-thumbnail/sunday-times-01.jpg',
    isWide: false,
    imagesPath: [
      `/assets/14/1.jpg`,
      `/assets/14/2.jpg`,
      `/assets/14/3.jpg`,
      `/assets/14/4.jpg`,
    ],
  },
  {
    id: 19,
    name: 'THE COLLECTOR - SUNGLASSES AT NIGHT',
    slug: 'the-collector-sunglasses-at-night',
    category: 'PH: ADRIANO RUSSO, \nSTYLIST: CLAUDIA GASTALDI',
    imagePath: '/assets/projects-thumbnail/collector-01.jpg',
    isWide: false,
    imagesPath: [
      `/assets/16/1.jpg`,
      `/assets/16/2.jpg`,
      `/assets/16/3.jpg`,
      `/assets/16/4.jpg`,
      `/assets/16/5.jpg`,
      `/assets/16/6.jpg`,
      `/assets/16/7.jpg`,
    ],
  },
  {
    id: 20,
    name: 'MIA LE JOURNAL – HOW DO YOU FEEL',
    slug: 'mia-le-journal-feminin-singulier',
    category:
      'PH: ADRIANO RUSSO, \nSTYLIST: ELISABETTA CAVATORTA',
    imagePath: '/assets/projects-thumbnail/mialejournal-01.jpg',
    isWide: false,
    imagesPath: [
      `/assets/17/1.jpg`,
      `/assets/17/2.jpg`,
      `/assets/17/3.jpg`,
      `/assets/17/4.jpg`,
      `/assets/17/5.jpg`,
      `/assets/17/6.jpg`,
      `/assets/17/7.jpg`,
    ],
  },
  {
    id: 21,
    name: 'GIORGIO ARMANI NEVE 2021',
    slug: 'giorgio-armani-neve',
    category:
      'GIORGIO ARMANI NEVE - VIDEO DIRECTOR DANIEL CLAVERO - STYLIST CAROLA BIANCHI',
    imagePath: '/assets/projects-thumbnail/neve-2.jpg',
    isWide: false,
    isVideo: true,
    videoPath: '/assets/44/neve.mp4',
  },
  {
    id: 22,
    name: 'ELLE ITALIA – LA BELLA VITA',
    slug: 'elle-italia-la-bella-vita',
    category:
      'PH: LAURA SCIACOVELLI, \nSTYLIST: MONICA CURETTI, \n LOCATION: COMO LAKE(IT)',
    imagePath: '/assets/projects-thumbnail/elleit_01.jpg',
    isWide: false,
    imagesPath: [
      `/assets/18/1.jpg`,
      `/assets/18/2.jpg`,
      `/assets/18/3.jpg`,
      `/assets/18/5.jpg`,
      `/assets/18/6.jpg`,
    ],
  },
  {
    id: 23,
    name: 'CORNELIANI ADV FW2020',
    slug: 'corneliani-adv-fw2020',
    category:
      'PH: THOMAS LOHR, \nSTYLIST: JULIAN GANIO, \nART DIRECTOR: PABLO ARROYO',
    imagePath: '/assets/projects-thumbnail/corneliani-03-01.jpg',
    isWide: false,
    imagesPath: [
      `/assets/24/1.jpg`,
      `/assets/24/2.jpg`,
      `/assets/24/3.jpg`,
    ],
  },
  {
    id: 24,
    name: 'EA7 ARMANI SS2020',
    slug: 'ea7-armani-ss20',
    category: ' PH: SERGE GUERARD, \nSTYLIST: LUDOVICA NANNI, \nLOCATION: SARDINIA',
    imagePath: '/assets/projects-thumbnail/ea7-01.jpg',
    isWide: false,
    imagesPath: [
      `/assets/20/1.jpg`,
      `/assets/20/2.jpg`,
      `/assets/20/3.jpg`,
    ],
  },
  {
    id: 25,
    name: 'EA7 ARMANI SS2020 - VIDEO',
    slug: 'ea7-armani-ss20-video',
    category: ' PH: SERGE GUERARD, \nSTYLIST: LUDOVICA NANNI, \nLOCATION: SARDINIA',
    imagePath: '/assets/projects-thumbnail/ea7-02.jpg',
    isWide: false,
    isVideo: true,
    videoPath: '/assets/44/ea.mp4',
  },
  {
    id: 26,
    name: 'ERMENEGILDO ZEGNA SS2020',
    slug: 'ermenegildo-zegna-ss20',
    category:
      'PH: PIERRE TOUSSAINT, \nCREATIVE DIRECTORS: \nALESSANDRO SARTORI \nE JERRY LORENZO, \nPRODUCTION: INTERLUDE PROJECT',
    imagePath: '/assets/projects-thumbnail/ermenegildo-zegna-01.jpg',
    isWide: false,
    imagesPath: [
      `/assets/21/1.jpg`,
      `/assets/21/2.jpg`,
      `/assets/21/3.jpg`,
    ],
  },
  {
    id: 27,
    name: 'MIA LE JOURNAL – ANNA IN WONDERLAND',
    slug: 'mia-le-journal-anna-in-wonderland',
    category:
      'PH: ADRIANO RUSSO, STYLIST: ELISABETTA CAVATORTA, \nTALENT: ANNA CLEVELAND, \n LOCATION: COMO LAKE',
    imagePath:
      '/assets/projects-thumbnail/mialejournal-annainwonderland-01.jpg',
    isWide: false,
    imagesPath: [
      `/assets/22/1.jpg`,
      `/assets/22/2.jpg`,
      `/assets/22/3.jpg`,
      `/assets/22/4.jpg`,
      `/assets/22/6.jpg`,
    ],
  },
  {
    id: 28,
    name: 'FALCONERI FW2019/20',
    slug: 'falconeri-fw-19-20',
    category: 'PH: ADRIANO RUSSO, \nSTYLIST: VIVIANA VOLPICELLA, \nLOCATIOn: COURMAYEOUR (AO)',
    imagePath: '/assets/projects-thumbnail/falconeri-01.jpg',
    isWide: false,
    imagesPath: [
      `/assets/23/1.jpg`,
      `/assets/23/2.jpg`,
      `/assets/23/3.jpg`,
    ],
  },
  {
    id: 29,
    name: 'CORNELIANI SS2020',
    slug: 'corneliani-ss20',
    category: 'PH: ADRIANO RUSSO, \nSTYLIST: EMIL REBEK',
    imagePath: '/assets/projects-thumbnail/corneliani-04-01.jpg',
    isWide: true,
    imagesPath: [
      `/assets/19/1.jpg`,
      `/assets/19/2.jpg`,
      `/assets/19/3.jpg`,
      `/assets/19/4.jpg`,
    ]
  },
  {
    id: 30,
    name: 'ELLE UK – THINK YOU KNOW KATIE HOLMES?',
    slug: 'elle-uk-think-you-know-katie-holmes',
    category: 'PH: DANIEL CLAVERO, \nSTYLIST: SASA THOMAN, \nTALENT: KATIE HOLMES',
    imagePath: '/assets/projects-thumbnail/elleuk-katieholmes-01.jpg',
    isWide: false,
    imagesPath: [
      `/assets/25/1.jpg`,
      `/assets/25/2.jpg`,
      `/assets/25/3.jpg`,
      `/assets/25/4.jpg`,
      `/assets/25/5.jpg`,
      `/assets/25/6.jpg`,
      `/assets/25/7.jpg`,
    ],
  },
  {
    id: 31,
    name: 'CESARE PACIOTTI SS2019',
    slug: 'cesare-paciotti-ss19',
    category:
      'ART DIRECTION: BRAGA+FEDERICO \nVIDEO DIRECTOR: FRANCESCO BONASIA E FABRIZIO NARCISI, \nSTYLIST: ADA KOKOSAR,',
    imagePath: '/assets/projects-thumbnail/cesare-pacciotti-02.jpg',
    isWide: true,
    isVideo: true,
    videoPath: '/assets/26/Paciotti.mp4',
  },
  {
    id: 32,
    name: 'ZALANDO',
    slug: 'zalando',
    category: 'PH: ALICE ROSATI, \nSTYLIST: GIORGIA TAL',
    imagePath: '/assets/projects-thumbnail/zalando-01.jpg',
    isWide: false,
    isVideo: true,
    imagesPath: [
      `/assets/27/1.jpg`,
      `/assets/27/2.jpg`,
      `/assets/27/3.jpg`,
    ],
  },
  {
    id: 33,
    name: 'CORNELIANI ADV FW2019',
    slug: 'corneliani-adv-fw2019',
    category:
      'PH: DANIEL RIERA, \nSTYLIST: JULIAN GANIO, \nART DIRECTOR: PABLO ARROYO',
    imagePath: '/assets/projects-thumbnail/corneliani-02-01.jpg',
    isWide: true,
    imagesPath: [
      `/assets/28/1.jpg`,
      `/assets/28/2.jpg`,
      `/assets/28/3.jpg`,
      `/assets/28/4.jpg`,
    ],
  },
  {
    id: 34,
    name: 'MSGM',
    slug: 'msgm-bar-basso',
    category:
      'PH: ALASDAIR MCLELLAN, \nSTYLIST & CREATIVE DIRECTOR: KATIE GRAND, \nLOCATION: BAR BASSO MILANO',
    imagePath: '/assets/projects-thumbnail/barbasso1.jpg',
    isWide: true,
    imagesPath: [
      `/assets/29/1.jpg`,
      `/assets/29/2.jpg`,
      `/assets/29/3.jpg`,
      `/assets/29/4.jpg`,
    ],
  },
  {
    id: 35,
    name: 'GOLDENPOINT MARE 2019',
    slug: 'goldenpoint-mare-2019',
    category:
      'PH: ADRIANO RUSSO, \nSTYLIST: CLAUDIA GASTALDI, \nModels: ALENA BLOHM, \nLOCATION FORMENTERA (ES)',
    imagePath: '/assets/projects-thumbnail/goldenpoint-02-01.jpg',
    isWide: false,
    imagesPath: [
      `/assets/30/1.jpg`,
      `/assets/30/2.jpg`,
      `/assets/30/3.jpg`,
      `/assets/30/4.jpg`,
      `/assets/30/5.jpg`,
    ],
  },
  {
    id: 36,
    name: 'CESARE PACIOTTI FW2018/19',
    slug: 'cesare-paciotti-fw18-19',
    category:
      'PH: ALESSIO BONI, \nSTYLIST ADA KOKOSAR, \nART DIRECTION: BRAGA+FEDERICO, \nMODEL: BETTE FRANKE',
    imagePath: '/assets/projects-thumbnail/cesarepaciotti-thumbnail.jpg',
    isWide: true,
    imagesPath: [
      `/assets/31/1.jpg`,
      `/assets/31/2.jpg`,
      `/assets/31/3.jpg`,
    ],
  },
  {
    id: 37,
    name: 'SISLEY YOUNG SS2018',
    slug: 'sisley-young-ss18',
    category:
      'PH: ADRIANO RUSSO, \nSTYLIST: VIVIANA VOLPICELLA, \nART DIRECTION: BRAGA+FEDERIO, \nLOCATION PUGLIA (IT)',
    imagePath: '/assets/projects-thumbnail/sisley-young-02-01.jpg',
    isWide: true,
    imagesPath: [
      `/assets/32/1.jpg`,
      `/assets/32/2.jpg`,
      `/assets/32/3.jpg`,
      `/assets/32/4.jpg`,
      `/assets/32/5.jpg`,
      `/assets/32/6.jpg`,
      `/assets/32/7.jpg`,
      `/assets/32/8.jpg`,
    ],
  },
  {
    id: 38,
    name: 'MAX MARA STUDIO SS2017',
    slug: 'max-mara-studio-ss17',
    category: 'PH: GIAMPAOLO SGURA, \nSTYLIST: SISSY VIAN',
    imagePath: '/assets/projects-thumbnail/maxmara-01.jpg',
    isWide: false,
    imagesPath: [
      `/assets/33/1.jpg`,
      `/assets/33/2.jpg`,
      `/assets/33/3.jpg`,
      `/assets/33/4.jpg`,
      `/assets/33/5.jpg`,
    ],
  },
  {
    id: 39,
    name: 'GOLDENPOINT MARE 2017',
    slug: 'goldenpoint-mare-17',
    category:
      'PH: ADRIANO RUSSO, \nSTYLIST: CLAUDIA GASTALDI, \nLOCATION FORMENTERA(ES)',
    imagePath: '/assets/projects-thumbnail/goldenpoint-01.jpg',
    isWide: true,
    imagesPath: [
      `/assets/34/1.jpg`,
      `/assets/34/2.jpg`,
      `/assets/34/3.jpg`,
      `/assets/34/4.jpg`,
      `/assets/34/5.jpg`,
      `/assets/34/6.jpg`,
      `/assets/34/7.jpg`,
      `/assets/34/8.jpg`,
    ],
  },
  {
    id: 40,
    name: 'CORNELIANI ADV FW2017/18',
    slug: 'corneliani-adv-fw17-18',
    category:
      'PH: BRUNO STAUB, \nSTYLIST: JEROME ANDRÉ, \nART DIRECTOR: PABLO ARROYO \n LOCATION: TURIN',
    imagePath: '/assets/projects-thumbnail/corneliani-01-01.jpg',
    isWide: false,
    imagesPath: [
      `/assets/35/1.jpg`,
      `/assets/35/2.jpg`,
      `/assets/35/3.jpg`,
      `/assets/35/4.jpg`,
    ],
  },
  {
    id: 41,
    name: 'CESARE PACIOTTI SS2017',
    slug: 'cesare-paciotti-ss17',
    category:
      'PH: SEAN&SENG, \nSTYLIST: MARGHERITA MORO, \nART DIRECTION: BRAGA+FEDERICO, \nMODEL: MATHILDE BRANDI',
    imagePath: '/assets/projects-thumbnail/cesarepaciotti-2.jpg',
    isWide: true,
    imagesPath: [
      `/assets/36/1.jpg`,
      `/assets/36/2.jpg`,
      `/assets/36/3.jpg`,
      `/assets/36/4.jpg`,
      `/assets/36/5.jpg`,
    ],
  },
  {
    id: 42,
    name: 'SISLEY YOUNG SS2017',
    slug: 'sisley-young-ss17',
    category:
      'PH: ADRIANO RUSSO, \nSTYLIST: VIVIANA VOLPICELLA, \nART DIRECTION: BRAGA+FEDERICO',
    imagePath: '/assets/projects-thumbnail/sisley-young-1.jpg',
    isWide: false,
    imagesPath: [
      `/assets/37/1.jpg`,
      `/assets/37/2.jpg`,
      `/assets/37/3.jpg`,
      `/assets/37/4.jpg`,
      `/assets/37/5.jpg`,
      `/assets/37/6.jpg`,
    ],
  },
  {
    id: 43,
    name: 'PAL ZILERI SS2017',
    slug: 'pal-zileri-ss17',
    category:
      'PH: DYLAN DON, \nSTYLIST: ANDREA TENERANI, \nTALENT: MATTHEW GOODE\n LOCATION MURALLA ROJA (ALICANTE - ES)',
    imagePath: '/assets/projects-thumbnail/palzileri001.jpg',
    isWide: true,
    imagesPath: [
      `/assets/38/1.jpg`,
      `/assets/38/2.jpg`,
      `/assets/38/3.jpg`,
      `/assets/38/4.jpg`,
    ],
  },
  {
    id: 44,
    name: 'GQ China - Wildlife',
    slug: 'gq-china-wildlife',
    category: 'PH: GIAMPAOLO SGURA, \nSTYLIST: GRANT PEARCE',
    imagePath: '/assets/projects-thumbnail/gq-wildlife.jpg',
    isWide: true,
    imagesPath: [
      `/assets/39/1.jpg`,
      `/assets/39/2.jpg`,
      `/assets/39/3.jpg`,
      `/assets/39/4.jpg`,
    ],
  },
  {
    id: 45,
    name: 'GQ China - Madness',
    slug: 'gq-china-madness',
    category:
      'PH: ADRIANO RUSSO, \nSTYLIST: JACKIE TAM',
    imagePath: '/assets/projects-thumbnail/gq-madness.jpg',
    isWide: true,
    imagesPath: [
      `/assets/44/1.jpg`,
      `/assets/44/2.jpg`,
      `/assets/44/3.jpg`,
    ],
  },
  {
    id: 46,
    name: 'VOGUE BRASIL - COSA NOSTRA',
    slug: 'vogue-brasil-cosa-nostra',
    category:
      'PH: ADRIANO RUSSO,\nSTYLIST: VIVIANA VOLPICELLA, \n MODELL: CHIARA SCELSI',
    imagePath: '/assets/projects-thumbnail/01-vogue.jpg',
    isWide: true,
    imagesPath: [
      `/assets/40/1.jpg`,
      `/assets/40/2.jpg`,
      `/assets/40/3.jpg`,
      `/assets/40/4.jpg`,
    ],
  },
]
